### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by venkateshchittinidi** [anantSinghCross/hand-gesture-recognition#1]
ValueError                                Traceback (most recent call last)
<ipython-input-1-5965db618760> in <module>
    113         else:
    114             # segment the hand region
--> 115             hand = segment(gray)
    116 
    117             # check whether hand region is segmented

<ipython-input-1-5965db618760> in segment(image, threshold)
     34     # threshold the diff image so that we get the foreground
     35     thresholded = cv2.threshold(diff, threshold, 255, cv2.THRESH_BINARY)[1]
---> 36     (_, cnts, _) = cv2.findContours(thresholded.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
     37     if len(cnts) == 0:
     38         return

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by cardboardcode** [comment]
Change the line to:

`(cnts, _) = cv2.findContours(thresholded.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)`

**Comment by 1nF0rmed** [comment]
@cardboardcode solution works as with OpenCV>=4.0. @anantSinghCross Please close this issue.
